name: PR Checks

on:
  pull_request_target:
    branches:
      - main # Change if your default branch is different

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Success
        run: echo "Workflow completed successfully."
